name: Push Json

on:
  schedule:
    - cron: '0/5 * * * * ? '

jobs:
  pushJson:
    name: Push Json
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Node 12.x
        uses: actions/setup-node@v2-beta
        with:
          node-version: 12.x

      - name: Install Packages
        run: npm install

      - name: Execute
        run: node index.js
        env:
          barkurl: 'https://api.day.app/FdYx53YpGBP8t6fMgVfyNP/' # 请替换为您自己的 bark 推送链接
          huoqujson: ${{ secrets.huoqujson }} # 添加您在 GitHub Secrets 中设置的 huoqujson 的值
